# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dist: bionic

branches:
  only:
    - master

before_script:
  - python --version

script:
  - make test
  - if which python3 2> /dev/null ; then
      make clean;
      python3 --version;
      make test PYTHON=python3;
    fi

matrix:
  include:
    - os: linux
      group: travis_latest
      language: python
      python: "2.7"

    - os: linux
      group: travis_latest
      language: python
      python: "3.5"

    - os: linux
      group: travis_latest
      language: python
      python: "3.6"

    - os: linux
      group: travis_latest
      language: python
      python: "3.7"

    - os: linux
      group: travis_latest
      language: python
      python: "3.8"

    - os: osx
      osx_image: xcode9.2
      language: shell
      # This is the last version of macOS 10.12 available on Travis CI.
      name: "Xcode 9.2 on macOS 12"

    - os: osx
      osx_image: xcode10.1
      language: shell
      # This is the last version of macOS 10.13 available on Travis CI.
      name: "Xcode 10.1 on macOS 10.13"

    - os: osx
      osx_image: xcode10.3
      language: shell
      # This is the last version of Xcode 10.x available on Travis CI.
      name: "Xcode 10.3 on macOS 10.13"

    - os: osx
      osx_image: xcode11
      language: shell
      name: "Xcode 11.0 on macOS 10.14"

    - os: osx
      osx_image: xcode11.1
      language: shell
      name: "Xcode 11.1 on macOS 10.14"

    - os: osx
      osx_image: xcode11.2
      language: shell
      name: "Xcode 11.2.1 on macOS 10.14"

    - os: osx
      osx_image: xcode11.3
      language: shell
      name: "Xcode 11.3.1 on macOS 10.14"

  allow_failures:
    - os: osx

  fast_finish: true
