# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Typecheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
      #
      #      ┌───────────── minute (0 - 59)
      #      │ ┌───────────── hour (0 - 23)
      #      │ │ ┌───────────── day of the month (1 - 31)
      #      │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
      #      │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
      #      │ │ │ │ │
    - cron: '1 2 3 * *'  # run at 2:01 every month on the 3rd day

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-24.04' ]
        python: [ '3.13', '3.12', '3.11' ]
    name: Python ${{ matrix.python }} (${{ matrix.os }})
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install general Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Python deps for Mypy typechecking tests
        run: python -m pip install -r requirements-mypy.txt

      - name: Check types with Mypy
        run: make mypy-test PYTHON_VERSION=${{ matrix.python }} VERBOSE=1
        # Mark this check optional for now, in case it starts out failing.
        # We will make it required once we've fixed any existing issues.
        continue-on-error: true

      - name: Install Python deps for PyType typechecking tests
        run: python -m pip install -r requirements-pytype.txt
        # https://github.com/google/pytype/issues/1475
        #
        # PyType does not yet support Python 3.12 or later; if this step is
        # enabled, it fails with an error: "Python versions > 3.11 are not yet
        # supported."
        if: ${{ (matrix.python != '3.13') && (matrix.python != '3.12') }}

      - name: Check types with PyType
        run: make pytype-test PYTHON_VERSION=${{ matrix.python }} VERBOSE=1
        # https://github.com/google/pytype/issues/1475
        #
        # PyType does not yet support Python 3.12 or later; if this step is
        # enabled, it fails with an error: "Python versions > 3.11 are not yet
        # supported."
        if: ${{ (matrix.python != '3.13') && (matrix.python != '3.12') }}
